server:
  port: 7079
spring:
  application:
    name: server-feign
  zipkin:
    base-url: http://localhost:7082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    hostname:feign
ribbon:
  eureka:
    enabled: true
    